version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: hackistan_postgres
    restart: always
    environment:
      POSTGRES_USER: hackistan
      POSTGRES_PASSWORD: hackistan
      POSTGRES_DB: hackistan_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hackistan"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: hackistan_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres

  backend:
    build:
      context: ../apps/backend
      dockerfile: Dockerfile.dev
    container_name: hackistan_backend
    restart: always
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: development
      PORT: 4000
      DATABASE_URL: postgres://hackistan:hackistan@postgres:5432/hackistan_db
    volumes:
      - ../apps/backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
    command: sh -c "pnpm install && pnpm exec ts-node src/index.ts"
  
  frontend:
    build:
      context: ../apps/frontend
      dockerfile: Dockerfile.dev
    container_name: hackistan_frontend
    restart: always
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:4000/api
    volumes:
      - ../apps/frontend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - backend
    command: sh -c "pnpm install && pnpm exec vite --host"

volumes:
  postgres-data:
  pgadmin-data: